version: "3"

services:
  role-script:
    restart: unless-stopped
    image: role_script
    build: ./role_script
    environment:
      - SQL_USER=osp
      - SQL_PASS=internalanywayDSfagWgmUUnF
      - SQL_DB=osp
      - SQL_HOST=db
